"""Regression checks for relocation behavioral contract."""

from __future__ import annotations

import csv
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[2]
BACK_BASE_DIR = REPO_ROOT / "back-base"
ENTRYPOINT = BACK_BASE_DIR / "etl_naranjax.py"
INPUT_WORKBOOK = BACK_BASE_DIR / "archivo-recibido" / "Formato completo de archivo de entrada.xlsx"
LEGACY_BASELINE = BACK_BASE_DIR / "base-generada" / "NARANJAX_CARTERA_20260417.csv"
GOLDEN_HEADER = Path(__file__).with_name("golden_output_header.txt")


sys.path.insert(0, str(BACK_BASE_DIR))


from back_base_etl.constants import AMOUNT_INPUT_COLS, OUTPUT_COLUMNS  # noqa: E402


class RelocationContractTests(unittest.TestCase):
    """Validate schema stability and relocation equivalence evidence."""

    @classmethod
    def setUpClass(cls) -> None:
        if not INPUT_WORKBOOK.exists():
            raise unittest.SkipTest(
                f"Input workbook unavailable for relocation contract test: {INPUT_WORKBOOK}"
            )
        cls._tmpdir = tempfile.TemporaryDirectory()
        cls.output_dir = Path(cls._tmpdir.name)

        run = subprocess.run(
            [
                sys.executable,
                str(ENTRYPOINT),
                "--input",
                str(INPUT_WORKBOOK),
                "--output_dir",
                str(cls.output_dir),
            ],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        if run.returncode != 0:
            raise AssertionError(
                "Smoke execution failed in regression setup.\n"
                f"stdout:\n{run.stdout}\n"
                f"stderr:\n{run.stderr}"
            )

        generated_files = sorted(cls.output_dir.glob("NARANJAX_CARTERA_*.csv"))
        if not generated_files:
            raise AssertionError("No output CSV generated by smoke execution.")
        cls.generated_output = generated_files[-1]

    @classmethod
    def tearDownClass(cls) -> None:
        cls._tmpdir.cleanup()

    def test_output_header_matches_golden_contract(self) -> None:
        expected_header = GOLDEN_HEADER.read_text(encoding="utf-8").strip().split(";")

        self.assertEqual(expected_header, OUTPUT_COLUMNS)

        with self.generated_output.open("r", encoding="utf-8", newline="") as csv_file:
            reader = csv.reader(csv_file, delimiter=";")
            generated_header = next(reader)

        self.assertEqual(generated_header, expected_header)

    def test_same_input_comparable_output_contract_against_legacy_artifact(self) -> None:
        if not LEGACY_BASELINE.exists():
            self.skipTest(
                "Legacy baseline output is unavailable; cannot run pre/post proxy check."
            )

        baseline_df = pd.read_csv(LEGACY_BASELINE, sep=";", dtype=str, keep_default_na=False)
        current_df = pd.read_csv(self.generated_output, sep=";", dtype=str, keep_default_na=False)

        if "id_nro_documento" in baseline_df.columns and "id_nro_dni" not in baseline_df.columns:
            baseline_df = baseline_df.rename(columns={"id_nro_documento": "id_nro_dni"})

        for column in OUTPUT_COLUMNS:
            if column not in baseline_df.columns:
                baseline_df[column] = ""
            if column not in current_df.columns:
                current_df[column] = ""

        baseline_df = baseline_df[OUTPUT_COLUMNS]
        current_df = current_df[OUTPUT_COLUMNS]

        self.assertEqual(list(current_df.columns), OUTPUT_COLUMNS)
        self.assertEqual(list(baseline_df.columns), OUTPUT_COLUMNS)
        self.assertEqual(len(current_df), len(baseline_df))

        self.assertEqual(
            (current_df["id_nro_dni"].str.strip() != "").sum(),
            (baseline_df["id_nro_dni"].str.strip() != "").sum(),
        )
        self.assertEqual(
            (current_df["tel_1"].str.strip() != "").sum(),
            (baseline_df["tel_1"].str.strip() != "").sum(),
        )

        for amount_col in AMOUNT_INPUT_COLS:
            current_sum = pd.to_numeric(current_df[amount_col], errors="coerce").fillna(0).sum()
            baseline_sum = pd.to_numeric(baseline_df[amount_col], errors="coerce").fillna(0).sum()
            self.assertAlmostEqual(current_sum, baseline_sum, places=2, msg=amount_col)


if __name__ == "__main__":
    unittest.main()
